# Print available options
default:
    @just --list --unsorted

#  Run the example retrieving all the open orders
orders:
    cargo -q run --bin orders

#  Run the example subscribing to the RFQ WebSocket
rfq:
    cargo -q run --bin rfq

#  Run the example to retrieve markets
markets:
    cargo -q run --bin markets


#  Run the example to retrieve depth
depth symbol="SOL_USDC_PERP" limit="5":
    cargo -q run --bin depth -- --symbol {{symbol}} --limit {{limit}}

#  Run the example to retrieve user information and permissions
user:
    cargo -q run --bin user
