# Print available options
default:
    @just --list --unsorted

#  Run the example retrieving all the open orders
orders:
    cargo -q run --bin orders

#  Run the example subscribing to the RFQ WebSocket
rfq:
    cargo -q run --bin rfq
