name: audit

on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  schedule:
    - cron: "0 0 * * *"

jobs:
  audit:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cargo-audit
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-audit
          locked: true

      - name: Audit
        run: cargo audit
